name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      customer:
        description: Customer Name
        required: true
        default: ABC

      environment:
        description: Environment
        required: true
        default: QA

jobs:
  my-first-manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Current Directory
        run: pwd

      - name: Show Files
        run: ls -la

      - name: Show Inputs
        run: |
          echo "Customer: ${{github.event.inputs.customer}}"
          echo "Environment: ${{github.event.inputs.environment}}"
